# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleHasHashTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.Article')),
                ('hashtag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.HashTag')),
            ],
        ),
    ]
