# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_articlehashashtag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlehashashtag',
            name='article',
        ),
        migrations.RemoveField(
            model_name='articlehashashtag',
            name='hashtag',
        ),
        migrations.AddField(
            model_name='article',
            name='hashtag',
            field=models.ManyToManyField(to='feed.HashTag'),
        ),
        migrations.DeleteModel(
            name='ArticleHasHashTag',
        ),
    ]
